"""empty message

Revision ID: 68b5b4f52470
Revises: 71ddd9d68a58
Create Date: 2025-04-04 17:11:43.057382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68b5b4f52470"
down_revision: Union[str, None] = "71ddd9d68a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "money_balances",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    )
    op.add_column("money_balances", sa.Column("description", sa.String(), nullable=False))
    op.add_column("money_balances", sa.Column("amount", sa.Integer(), server_default="0", nullable=False))
    op.drop_column("money_balances", "balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "money_balances",
        sa.Column("balance", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
    )
    op.drop_column("money_balances", "amount")
    op.drop_column("money_balances", "description")
    op.drop_column("money_balances", "created_at")
    # ### end Alembic commands ###
