"""empty message

Revision ID: 71ddd9d68a58
Revises: 89712c2c7324
Create Date: 2025-03-31 19:27:15.486944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71ddd9d68a58"
down_revision: Union[str, None] = "89712c2c7324"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("money_balances", sa.Column("balance", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("money_balances", "balance")
    # ### end Alembic commands ###
