"""empty message

Revision ID: 89712c2c7324
Revises: 41fc29cc648d
Create Date: 2025-03-31 19:26:19.586245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89712c2c7324"
down_revision: Union[str, None] = "41fc29cc648d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("money_balances", "balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "money_balances",
        sa.Column(
            "balance",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
