"""empty message

Revision ID: de426d118818
Revises: 0b6e2a55786e
Create Date: 2025-06-22 15:37:29.076138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de426d118818"
down_revision: Union[str, None] = "0b6e2a55786e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bonds", sa.Column("cur_coupon", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bonds", "cur_coupon")
    # ### end Alembic commands ###
