when:
  - event: push
    branch: main

steps:
  - name: deploy
    image: docker:latest
    commands:
      - echo "$ENV_FILE"
      - echo "$ENV_FILE" > .env
      - docker-compose -f docker-compose.yml up -d --build
      - docker ps -a